from iterations import Iterations
from list_comprehensions import Comprehensions
from other_iteration_contexts import Contexts
from new_iterables import Iterables

def main():
    # Iterations: A First Look
    I = Iterations()
    I.example1()
    I.example2()
    I.example3()
    I.example4()
    I.example5()
    I.example6()
    I.example7()
    I.example8()
    I.example9()
    I.example10()
    I.example11()
    I.example12()
    I.example13()
    I.example14()
    I.example15()
    I.example16()
    I.example17()
    I.example18()
    I.example19()
    I.example20()

    # List Comprehensions: A First Detailed Look
    C = Comprehensions()
    C.example1()
    C.example2()
    C.example3()
    C.example4()
    C.example5()
    C.example6()
    C.example7()
    C.example8()
    C.example9()
    C.example10()
    C.example11()
    C.example12()
    C.example13()
    C.example14()
    C.example15()
    C.example16()
    C.example17()

    # Other Iteration Contexts
    IC = Contexts()
    IC.example1()
    IC.example2()
    IC.example3()
    IC.example4()
    IC.example5()
    IC.example6()
    IC.example7()
    IC.example8()
    IC.example9()
    IC.example10()
    IC.example11()
    IC.example12()
    IC.example13()
    IC.example14()
    IC.example15()
    IC.example16()
    IC.example17()
    IC.example18()
    IC.example19()
    IC.example20()
    IC.example21()
    IC.example22()
    IC.example23()
    IC.example24()
    IC.example25()
    IC.example26()
    IC.example27()
    IC.example28()
    IC.example29()
    IC.example30()
    IC.example31()

    # New Iterables in Python 3.X
    IT = Iterables()
    IT.example1()
    IT.example2()
    IT.example3()
    IT.example4()
    IT.example5()
    IT.example6()
    IT.example7()
    IT.example8()
    IT.example9()
    IT.example10()
    IT.example11()
    IT.example12()
    IT.example13()
    IT.example14()
    IT.example15()
    IT.example16()
    IT.example17()
    IT.example18()
    IT.example19()


if __name__ == "__main__":
    main()